### ISSUE TITLE
hard redirect torrentparadise.ml to torrent-paradise.ml

### ISSUE THREAD

**Issue by tycho01** [urbanguacamole/torrent-paradise#13]
The app is now hosted at both `torrent-paradise.ml` (canonical) and `torrentparadise.ml`.
The latter, however, does not work. Internally it still points its requests to the canonical domain, resulting in a CORS error.
I think doing a permanent redirect to the canonical domain should address this.

**Comment by urbanguacamole** [comment]
fixed, requests now go straight to torrentparadise.ml/api

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
