### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by varbhat** [urbanguacamole/torrent-paradise#23]
Where can i find it?

**Comment by urbanguacamole** [comment]
It's not an API in the sense that it's designed to be used by the public, so no documentation. But a look at the [source code](https://github.com/urbanguacamole/torrent-paradise/blob/master/api/main.go#L90) and the typical[ responses](https://torrent-paradise.ml/api/search?q=ubuntu%2016) should be enough if you want to use it in your app.

**Comment by varbhat** [comment]
So,basically you call,

https://torrent-paradise.ml/api/search?q=`query`

and you get json response containing array which has id,name,text,len,s,l .

**Comment by urbanguacamole** [comment]
Yes
