### ISSUE TITLE
Add dumps of Torrent sites

### ISSUE THREAD

**Issue by varbhat** [urbanguacamole/torrent-paradise#24]
Hey,there.

I think that torrent-paradise can be populted with torrent dumps of other sites to increase number of torrents available.

1) https://archive.org/details/TORRENTSMAGNETARCHIVES

2) https://the-eye.eu/public/Site-Dumps/torrent_dumps/

3) https://archiveteam.org/index.php?title=The_Pirate_Bay

**Comment by urbanguacamole** [comment]
You do not list the sizes of these dumps. I already use a 10M [Magnetico Community dump](https://github.com/boramalper/magnetico/issues/218) and update that often. I don't think there is much low-hanging fruit in adding all kinds of torrent dumps.
