### ISSUE TITLE
Refresh rate

### ISSUE THREAD

**Issue by TheAceShinigami** [urbanguacamole/torrent-paradise#25]
the last index update was 21/7/2020. Why does it not update more regularly. I'm probably misunderstanding some aspect of how it works

**Comment by marius851000** [comment]
AFAIK, only the IPFS index is outdated. The website seem to be up to date...

**Comment by TheAceShinigami** [comment]
the IPFS index is the whole selling point of the project, if it doesn't get updated I feel like that is a problem...

**Comment by urbanguacamole** [comment]
@TheAceShinigami @marius851000 

Updated, new IPFS index is rolling out now.
