### ISSUE TITLE
 Contribute to scraping

### ISSUE THREAD

**Issue by Tuxicoman2** [urbanguacamole/torrent-paradise#3]
Hi,

Maybe a silly question but how can we contribute to improve the content of the database?
Does everyone can modify the database?

**Comment by urbanguacamole** [comment]
The database is populated automatically by spidering the DHT. If you want to add a torrent to the database, create it and enable DHT for it and hope that it will get discovered by the spider.

**Comment by NatoBoram** [comment]
So it actually has to be a torrent for the spider to catch it? If, for example, I have a content on IPFS that I want to share, I have to make it available trough BitTorrent for it to appear on Torrent Paradise's IPFS node?

**Comment by urbanguacamole** [comment]
@NatoBoram yes, torrent-paradise searches only torrents. see ipfs-search.com for what you're looking for.
