### ISSUE TITLE
sqli bug

### ISSUE THREAD

**Issue by purpleidea** [urbanguacamole/torrent-paradise#30]
Found in <5 min
Probably a good idea to take security more seriously.
HTH

https://github.com/urbanguacamole/torrent-paradise/blob/19224e723c5b6c9a34009c8f3d75434412700231/spider/spider.go#L71

**Comment by trevyn** [comment]
Where is the bug here? I don’t believe that’s a string interpolation, and not sure what else you could be referring to.

**Comment by purpleidea** [comment]
You don't need to check bt.Name is safe before it's copied into $2?

**Comment by trevyn** [comment]
I don’t believe there’s a SQL injection here, if that’s what you mean; I believe the parameter is bound, not interpolated.

**Comment by urbanguacamole** [comment]
@purpleidea No, go sql takes care of it itself. There should be no SQL injection here.
