### ISSUE TITLE
Torrents not updating

### ISSUE THREAD

**Issue by julianfairfax** [urbanguacamole/torrent-paradise#37]
I sent you an email about this too but you mentioned that torrents found through rss should be updated within 6 hours, but it doesn't actually seem that is happening at the moment?

**Comment by urbanguacamole** [comment]
Oh god, now I see it. I fucked up the error handling, it failed silently. Will fix

**Comment by julianfairfax** [comment]
I guess it'll take time to update? It's good that it's fixed though!

**Comment by urbanguacamole** [comment]
@julianfairfax not fixed yet, I'm quite busy with other stuff rn :/ definitely will be fixed by EOY

**Comment by urbanguacamole** [comment]
Fixed in bf19077ad99a730945aec20247a877777da604eb
