### ISSUE TITLE
It seems torrent-paradise.ml/api/search no longer works

### ISSUE THREAD

**Issue by 3unjee** [urbanguacamole/torrent-paradise#38]
I get the following:
```
ipfs resolve -r /ipns/torrent-paradise.ml/api/search: no link named "api" under QmSHKiWWdfr1dPxgc6rqwnMJe6vRCiJE6j8xLkfEorw5hM
```

Is there a workaround for this ?

Thanks for the great work.

**Comment by simlei** [comment]
seconded; the search bar on the main page also doesn't work anymore:
```
bundle.js:199 Uncaught ReferenceError: passQueryToResultpage is not defined
    at searchTriggered (bundle.js:199)
    at HTMLButtonElement.onclick (index.html:50)
```

**Comment by 3unjee** [comment]
Yes, that's another issue not related to the API but I can reproduce on my side.

**Comment by urbanguacamole** [comment]
Server migration is finished, @3unjee @simlei now everything should work just like it did before.

**Comment by simlei** [comment]
thanks a lot!

**Comment by simlei** [comment]
This project is the highest improvement over a status quo i have seen for a long time btw. Great choice in tools and scope!

**Comment by 3unjee** [comment]
I second that, it's a great achievement -- And IPFS is a very important prospect for the coming years.

**Comment by swedneck** [comment]
This seems to still be happening, i just ran into it :/
