### ISSUE TITLE
ipfs link?

### ISSUE THREAD

**Issue by sdanfa** [urbanguacamole/torrent-paradise#39]
Hi,
I'm trying to access torrent-paradise 2.0 via ipfs but it gives me the wrong version. I tried ipfs://bafybeihi6s3spdznkj2jnbmihexzf5dgxocjcsqjgcl3rovi5ljlvzp5ty/ and /ipfs/QmPQDL1LUkgTYQY2kHrhrR7rP5Fu1Y3mEgshJo5oRQ5tCz

Both ipfs link versions are giving old results of torrents.

Thanks.

**Comment by urbanguacamole** [comment]
Hi, where did you find these links? They are indeed both for an old version. You can find fresh links here: https://torrent-paradise.ml/ipfs.html

**Comment by sdanfa** [comment]
Thanks for your quick reply. I had found the links randomly on Google and reddit. I tried the links from your url but the search button is not working. I tried multiple browsers and I have the same problem, search button won't work. I tried via local ipfs app and via external url like https://ipfs.io/ipns/torrent-paradise.ml/

**Comment by sdanfa** [comment]
Also this url won't load /ipns/12D3KooWB3GY1u6zMLqnf3MJ8zhX3SS1oBj7VXk3xp6sJJiFGZXp
