### ISSUE TITLE
Error when retrieve from cloudflare-ipfs.com

### ISSUE THREAD

**Issue by vuminhquang** [urbanguacamole/torrent-paradise#4]
Hello,

I get this error when connect to "https://cloudflare-ipfs.com/ipns/torrent-paradise.ml"
ipfs resolve -r /ipns/torrent-paradise.ml: could not resolve name

Seem that our site "torrent-paradise.ml" will be down if no public server
![image](https://user-images.githubusercontent.com/20512463/58777676-a13d2280-85f9-11e9-91c7-efc41ac29123.png)

Sincerely

**Comment by Mikaela** [comment]
I am seeing this also on localhost with IPFS Companion.

**Comment by urbanguacamole** [comment]
Fixed, made a mistake in the DNSLink.
