### ISSUE TITLE
Uncaught ReferenceError: `passQueryToResultpage` is not defined

### ISSUE THREAD

**Issue by luizcieslak** [urbanguacamole/torrent-paradise#40]
Hi! Since this is my first issue here, just wanna say that this is a great torrent search solution. Thank you for building this. 

Apparently there's an `Uncaught ReferenceError: passQueryToResultpage is not defined` when querying a search.
I'm not aware of the website architecture but it seems the static bundle.js file is not being loaded? Happy to help solving if needed!

**Comment by odomojuli** [comment]
`index.html` for the document iframe requires character encoding.

Console:
```
The character encoding of a framed document was not declared. The document may appear different if viewed without the document framing it. resultpage
Uncaught ReferenceError: passQueryToResultpage is not defined
    searchTriggered https://torrent-paradise.ml/bundle.js:199
    onclick https://torrent-paradise.ml/:1
bundle.js:199:5
```

Adding character encoding to`index.html` the result page may fix.
```
<head>
    <meta charset="utf-8">
    ...
</head>
```

**Comment by luizcieslak** [comment]
It seems to be back now? Gonna close this issue
