### ISSUE TITLE
Smartscreen reports ipfs site as unsafe

### ISSUE THREAD

**Issue by kotx** [urbanguacamole/torrent-paradise#48]
https://cloudflare-ipfs.com/ipfs/QmQjsKamNFZRvCMXDvZXQmRYjsmSkmZG5pBCTY4LtMj8hs/index.html is listed as unsafe, it might be worth it to report it as safe here: https://feedback.smartscreen.microsoft.com/feedback.aspx

**Comment by fislysandi** [comment]
unsafe my ass.

microsoft doesnt want you too get free shit.

**Comment by kotx** [comment]
Nah I found out it's just that all of https://cloudflare-ipfs.com/ipfs/ is marked as unsafe.
Just use a different gateway like ipfs.io: https://ipfs.io/ipfs/QmQjsKamNFZRvCMXDvZXQmRYjsmSkmZG5pBCTY4LtMj8hs/index.html
