### ISSUE TITLE
deep-link search for chromium omnibar quick-search

### ISSUE THREAD

**Issue by KiaraGrouwstra** [urbanguacamole/torrent-paradise#6]
I feel like torrent paradise is almost perfect -- thank you for making this and even making it open-source!
The one potential UX suggestion I could think of: using a Chromium-based browser (Brave), I like being able to search a website straight from the omnibar. For Torrent Paradise this doesn't currently work yet, I think because the search doesn't use its own URL / form.
If anyone would feel like it, I think this could be one way to make this even better. :)

**Comment by Artoria2e5** [comment]
I think this can be done in the HTML by checking the query parameters and filling the search box and calling `searchTriggered` automagiclly. But uh @urbanguacamole, is there a plan for reducing the code duplication between website and static versions?
