### ISSUE TITLE
torrent-paradise.ml redirects to external site

### ISSUE THREAD

**Issue by forkbomb9** [urbanguacamole/torrent-paradise#7]
The website (https://torrent-paradise.ml points to (REDACTED)
And the ipfs version https://cloudflare-ipfs.com/ipns/torrent-paradise.ml says `ipfs resolve -r /ipns/torrent-paradise.ml: could not resolve name`
I can still access through https://cloudflare-ipfs.com/ipns/12D3KooWB3GY1u6zMLqnf3MJ8zhX3SS1oBj7VXk3xp6sJJiFGZXp/

My assumption is that the domain expired, someone bought it and now our favorite torrent site is down.

**Comment by neozeed** [comment]
I'm getting the same...
Last index update: 8/9/2019

Guess should look at how to clone & run.

**Comment by urbanguacamole** [comment]
The website should be up now. 

What happened is that the DNS provider (Freenom) marked the domain as "fraud". They insist that on October 8 there was no content on the site and they decided it was fraud, didn't send me an email and redirected the domain (my domain) to another site.

I will take measures to prevent this from happening again. I'm truly sorry that this happened.

AFAIK ipfs.io/ipns/12D3KooWB3GY1u6zMLqnf3MJ8zhX3SS1oBj7VXk3xp6sJJiFGZXp was up the whole time. Decentralize everything!)

@neozeed you are welcome to clone the site, in case of any problems, send me an email

**Comment by urbanguacamole** [comment]
Also, in case this ever happens again (hopefully not), save /ipns/12D3KooWB3GY1u6zMLqnf3MJ8zhX3SS1oBj7VXk3xp6sJJiFGZXp (fresh) or /ipfs/QmZieTrQwQgi8AKH94b1Sck8j1NTtFExRJggdiKZhpekJ9/ (static) to access the site in the future

**Comment by urbanguacamole** [comment]
@neozeed if you want to clone the site, I've made a torrent with the full DB dump. [Here](https://github.com/urbanguacamole/torrent-paradise/blob/master/torrentparadise-staticbackup.torrent) is it, you're welcome

**Comment by forkbomb9** [comment]
@urbanguacamole Thanks! Didn't know that DNS providers could do that :thinking: Always learning new things...
BTW, sorry for linking the other site here, didn't think much about it.
Anyway, it's back!
