### ISSUE TITLE
Enhancement: More metadata info about torrents scrapped

### ISSUE THREAD

**Issue by Xandernardo** [urbanguacamole/torrent-paradise#8]
I really love this project, as, compared with others like it, is really simple yet efective.

The only problem I found when using it is that only knowing size, peers and seeders isn't enough to sane torrent search, as it is harder to spot fake torrents that could be potentially dangerous.

Other engines, like dhtcrawler2, doesn't check peer/seeders, but in contrast let you know when they were discovered, and the files the torrent has, lifting the burden of manually checking the torrent in your favorite BT client for that info.

So, I would humbly suggest, if it isn't already though, to add that into this project, which would make it stand appart from BiglyBT Swarm search option, which actually does mostly the same right now.

Thanks for your time and comprehension.

**Comment by Joepsh** [comment]
Does the Spider still work for you?

I see in the code that it checks the file sizes so it may be possible use that to filter out fake torrents [spider.go:59](https://github.com/urbanguacamole/torrent-paradise/blob/835dddeff34977dac6799156fe9f320093b5d99f/spider/spider.go#L59)

**Comment by urbanguacamole** [comment]
I already have data on when a torrent was discovered by my spider, but I don't think there's a reason to display it -- most of the torrents still come from The Pirate Bay dump and don't have a date attached to them.

I installed BiglyBT, but can't really get the swarm search to work. I've left it running for a few days, but it still can't seem to give me any real usable results.

Regarding files the torrent contains -- like @Joepsh mentioned, spider.go does receive a file list, but doesn't save it anywhere (only sums the individual file sizes to get the total size). I do not include a file list in the index, because I thought it would make the index too big, slowing down search, operations with it and complicating the distribution of the index.

**Comment by Joepsh** [comment]
@urbanguacamole I ran the spider on friday and was getting a lot of metadata but since then i get nothing. I still get OnPeerAnnounce but when i respond to get the metadata nothing is returned. I'm starting to think they are fake torrents. I am also seeing a lot of the same infohashes that start with the same hex values but end with different values i'm assuming someone is trying to flood the DHT with fake infohashes.

**Comment by urbanguacamole** [comment]
@Joepsh I'm unable to reproduce your problem. My DHT spider is running constantly and keeps adding between 300 and 3500 new torrents every day. This friday, it discovered 1601 new torrents and on sunday 3488. If someone is in fact flooding the DHT, then it's ineffective.

**Comment by Joepsh** [comment]
@urbanguacamole 

I don't know what is going on but i ran it 3 times and i was not seeing any OnAnnouncePeer messages but on the 4 try i started see them.

`2019/11/26 13:06:59 GetPeers: 1DC228C9B13808DA9EC21215E2C462D822C990B0 <188.232.17.121:16693>
2019/11/26 13:07:00 GetPeers: CF267B4A94BD2A5223CAA754F9293DAA3E06BAA6 <173.212.202.22:6969>
2019/11/26 13:07:00 GetPeers: 16CA235AF3F27BF14AC802F5E7D954ADC350D12E <203.206.40.247:51799>
{"infohash":"156a846b319f22d09806803de3716b030b6c5d88","name":"[HorribleSubs] Sengoku Night Blood - 05 [480p].mkv"}

2019/11/26 13:07:01 GetPeers: 0DA7B85F71371C73D0E1970A259B5DC4446E29C5 <207.180.192.206:39329>
2019/11/26 13:07:01 GetPeers: 53EF1C4D6BFED1D7A0D5CE845FC25298D3D711DE <37.21.146.197:22547>
2019/11/26 13:07:01 GetPeers: B952A4086BD2041F11CF8F8902DD06152185C068 <212.35.170.233:6105>
2019/11/26 13:07:01 GetPeers: F7F34D89908968AA6F0104C761D8D646BEC1F922 <1.172.92.65:7510>
2019/11/26 13:07:02 GetPeers: B952B91785082AD02F6E89EF3F282C5DECB5330B <5.189.183.129:27970>
2019/11/26 13:07:02 GetPeers: B952BD176D7EA85F0CEC1D704328833BECBC5BA4 <5.189.183.129:27970>
2019/11/26 13:07:02 AnnouncePeer: AACB4453B0F0FB1528FBD0A4C35CAC5A99A57001 <183.69.201.136:24547>
2019/11/26 13:07:02 GetPeers: 1BB7195B598D74C90862FEF101CBDBDED36AD610 <173.249.19.73:11989>
2019/11/26 13:07:03 AnnouncePeer: AACB4453B0F0FB1528FBD0A4C35CAC5A99A57001 <113.109.133.249:39703>
2019/11/26 13:07:03 GetPeers: B952A2EF8AF1066ECFC2A6A621AB2E3DF663F68D <5.189.183.129:46907>
2019/11/26 13:07:03 GetPeers: 1DC22DB2BC7DD962946F99F83FA25F1D47008B97 <213.136.79.27:51449>
2019/11/26 13:07:03 AnnouncePeer: F7F34D89908968AA6F0104C761D8D646BEC1F922 <150.116.46.248:8953>
2019/11/26 13:07:03 GetPeers: 7C1EA3C55E2DFA73A1C6A0C35FB8A6387BAA26D0 <115.235.147.224:7445>
2019/11/26 13:07:04 AnnouncePeer: 4939CD2A4011B4B7BF2F24CB865AFB77C37ADCF4 <121.32.193.89:13620>
2019/11/26 13:07:04 GetPeers: B67040003F511442A50F1015A6DEE04FAADCE5CC <173.249.44.166:57643>
2019/11/26 13:07:04 GetPeers: 7C1EA2E5F537B70619425FF037C2648CD83B49B4 <31.46.240.89:14717>
2019/11/26 13:07:05 AnnouncePeer: F7F348E2632A85A8254C755F5941C42FF3D4E896 <59.28.193.238:40842>
2019/11/26 13:07:05 AnnouncePeer: CD8A215D33B70118DB5B3243DA2E96F284AA90C3 <61.81.128.68:10024>
2019/11/26 13:07:05 GetPeers: 4E3F194B38908A12618CA6F8D8B44B825DC3A9B2 <37.212.27.29:6282>
2019/11/26 13:07:05 GetPeers: 7C1EA996E0C0D49942CF9B65BFD58B202B6DD380 <77.28.20.33:53950>
2019/11/26 13:07:06 AnnouncePeer: EEABD5D6BFA79CCF6513F261494540A8E9D07B49 <153.134.145.169:36945>
2019/11/26 13:07:06 GetPeers: AACB46947D015A2D0B7A9CFF906E02BC604801B4 <154.45.216.230:1184>
2019/11/26 13:07:06 GetPeers: 0DA7B7F7FBBDB3B0A43F8E8F03FB26DEA9D280B3 <52.34.68.33:8108>
2019/11/26 13:07:06 GetPeers: 9BD24CC8F4E195EA97EDC2C063D2C3FFAA6CB869 <179.35.206.140:6881>
2019/11/26 13:07:09 GetPeers: 2A4CF070AACDE40091727A2909200EA8A36BD820 <176.59.37.129:58793>
2019/11/26 13:07:09 AnnouncePeer: 9B9644CF96260A4D2B7A7ACE2D45FDCF5D76C31D <121.168.223.205:7539>
2019/11/26 13:07:10 GetPeers: 7D4DEB9607FE6E1EAF3AFE32753B2AB00AFA872D <115.235.147.224:7445>
2019/11/26 13:07:10 GetPeers: AACB4453B0F0FB1528FBD0A4C35CAC5A99A57001 <120.204.216.203:1641>
2019/11/26 13:07:10 GetPeers: AACB4453B0F0FB1528FBD0A4C35CAC5A99A57001 <36.104.199.23:4517>
2019/11/26 13:07:10 GetPeers: AACB4453B0F0FB1528FBD0A4C35CAC5A99A57001 <180.108.230.191:14647>
2019/11/26 13:07:10 GetPeers: 1BB71BD0EE5A76BDF1789F5B69868F16EA2BDC4A <188.126.61.165:59052>
2019/11/26 13:07:10 GetPeers: AACB454AB5E173FF720B5AE6EBBA1554C1D19857 <125.117.230.30:6832>
2019/11/26 13:07:10 GetPeers: AACB4453B0F0FB1528FBD0A4C35CAC5A99A57001 <123.153.53.3:6762>
2019/11/26 13:07:11 AnnouncePeer: AACB4453B0F0FB1528FBD0A4C35CAC5A99A57001 <114.231.146.165:45907>
2019/11/26 13:07:11 GetPeers: F27CA044C89754DB3D39DA374A1D5A97797BF294 <213.136.79.238:33457>
2019/11/26 13:07:11 GetPeers: 9BD24FA05126233B9FDCD4B2209B928B58A182C2 <179.35.206.140:6881>
2019/11/26 13:07:12 GetPeers: AACB4453B0F0FB1528FBD0A4C35CAC5A99A57001 <111.15.41.245:16069>
2019/11/26 13:07:12 GetPeers: 3BE637ED5BA7B3A854AAC5901B20A8F07C711E01 <147.30.28.17:44474>
2019/11/26 13:07:12 GetPeers: B952A48E2D833E3328BEA92D47E12D2E4276A943 <181.124.191.12:33320>
2019/11/26 13:07:12 GetPeers: EEABD6922B964F9173E37A9A3F3F39F824217913 <196.202.252.22:44694>
2019/11/26 13:07:12 AnnouncePeer: 7C1EA996E0C0D49942CF9B65BFD58B202B6DD380 <77.28.20.33:53950>
2019/11/26 13:07:13 GetPeers: 4939CD2A4011B4B7BF2F24CB865AFB77C37ADCF4 <59.60.214.159:22566>
2019/11/26 13:07:13 GetPeers: AACB4453B0F0FB1528FBD0A4C35CAC5A99A57001 <220.200.9.231:23360>
`

Only 1 out of all the info hashes returned any metadata that were being announced.

> I am also seeing a lot of the same infohashes that start with the same hex values but end with different values i'm assuming someone is trying to flood the DHT with fake infohashes.

`
GetPeers: 53EF09EE307655D48BE6566E4E7A66BAE0ADDDA1 <178.72.85.77:54677>
GetPeers: 53EF09EE307655D48BE657834AAE9AC2A8416D89 <178.72.85.77:54677>
`
The hash starts with the same values but ends differently and it's from the same ip address. I see a lot of them from different ips where the hashes seem to match up but are different.

It's very unlikely that both of those torrents are real and that ip is really trying to download them.
